Posts page feature
IanMcC123/Stoopify pull request #16
Opened 2024-04-28 23:31 UTC by George-Hachem

Posts are generated in the feed from newest to oldest. I also created a modal overlay for each post, which contains a description tab and a comment tab as well. In the description, there is a message and like button. The message button will create a conversation between the two users. The like button functions like the Instagram like button; if you press it for the first time, the number of likes increments and if you press is again it will decrease. I also added small details like owners of t posts will see a delete button on the top right of the post, they won't be able to like their own posts(because the like button is like a save button and there is no reason for owners to save their own posts, the posts will already be projected in their profiles), and the message button won't show on their own posts(since it does not make sense for users to message themselves).

2024-04-28 23:36 UTC, IanMcC123 commented
Great start George. Great demo. I think that there is room for potential future styling, but looks good for now.

2024-04-28 23:36 UTC, IanMcC123 approved these changes

2024-04-29 01:54 UTC, shihab3750 requested changes
clean up needed

2024-04-29 01:54 UTC, shihab3750 commented on frontend/src/pages/messaging/messaging.jsx
> +    //     const userId = newPostUserId ?? selectedUser[0]._id;
Can you remove this

2024-04-29 01:54 UTC, shihab3750 commented on frontend/src/pages/messaging/messaging.jsx
> +    //     }
not being used

2024-04-29 02:45 UTC, shihab3750 approved these changes
Approved

2024-04-29 02:45 UTC, merged